### ISSUE TITLE
[meta] v0.3 release checklist

### ISSUE THREAD

**Issue by formatc1702** [formatc1702/WireViz#245]
Tasks to do before v0.3 release.

- [ ] Add release date to `CHANGELOG.md` in `doc/changelog` branch
- [ ] Merge `doc/changelog` into `dev`
- [ ] Change `__version__` to `0.3`
- [ ] Rebuild examples
- [ ] Merge `dev` into `master`
- [ ] Add v0.3 tag to the merge commit and push tag
- [ ] Publish to PyPI
- [ ] Change `__version__` to `0.4-dev` in `dev` branch
